### ISSUE TITLE
sdist is missing from PyPI

### ISSUE THREAD

**Issue by crwood** [LeastAuthority/python-challenge-bypass-ristretto#34]
The [PyPI download files](https://pypi.org/project/python-challenge-bypass-ristretto/#files) for this project offers wheels for a few different platforms but currently lacks a source distribution. Users of platforms that are not already covered by one of the three wheels, therefore, must fetch the source code from GitHub -- and not PyPI -- in order to build and install the library.

It would be useful if an sdist could be provided alongside the existing wheels on PyPI so that users can install the library more directly (i.e., with a `python -m pip install python-challenge-bypass-ristretto` instead of `python -m pip install git+https://github.com/LeastAuthority/python-challenge-bypass-ristretto`).

**Comment by exarkun** [comment]
@crwood See https://github.com/LeastAuthority/python-challenge-bypass-ristretto/pull/50
